### PR TITLE
Create Die exercise instructions

### PR DESCRIPTION
**Pull request by samWson**
This was an exercise contributed from the Pharo community. It's not in the 'official' list of exercises so I think it never got a proper description.

This is to help fix the configlet error on #467.

### CODE REVIEW

**Comment by samWson** [comment]
@exercism/reviewers could I have someone approve this PR please?

**Review by BethanyG — APPROVED** [review]
LGTM!

**Comment by BethanyG** [comment]
@samWson  -- I will leave it to you to merge, just in case something else needs to be done.

**Review by SleeplessByte — APPROVED** [review]

**Comment by edward** [comment]
Thanks everyone!

**Pull request merged**
