### PR TITLE
Made download command more modular and intent revealing and extracted…

### PR DESCRIPTION
**Pull request by macta**
… out an ExercismSubmission object (vs. a Dictionary)

@bencoman @samWson - this is the start of trying to make the download/submit a little more modular (and a good practice session on TDD with a colleague).

Still more to do , but a start.

### CODE REVIEW

**Comment by macta** [comment]
And to expand - I'm trying to do it in an incremental way so that we can release it, and then do a bit more.

Ulimately I'm thinking that we have some slightly more obvious - download, submit and install commands - hopefully pulling out the http request into a composable object so that the tests don't actually impact the image and can run on the ci.

**Comment by macta** [comment]
Quick manual test in a fresh image seems to indicate this is all safe so far.

**Comment by macta** [comment]
@samWson @bencoman, I am ready to merge this branch.

While it looks quite big, its doesn't introduce any new functionality but separates things out for easier testing. Of note is that I have pulled in Mocketry (a mock library) to help with the testing. I've been very impressed with this library. There are still some tweaks to do, and we need the testing patterns to settle down, but overall I think it looks good. Check out [ExercismSubmitCommandTest](https://github.com/exercism/pharo-smalltalk/blob/81b60641fede07239719b9264d615d97907605a4/dev/src/ExercismTests/ExercismSubmitCommandTest.class.st)

**Comment by samWson** [comment]
I'm happy using Mocketry. I figured we were going to need mocks at some point if we were going to do proper testing. FYI I'm spending a lot of time going over our code to learn it so to speak. Our code base has grown fast and I haven't been able to keep up. So I'm spending time drawing diagrams to help make sense of it all which is why I haven't been active here lately.

**Comment by bencoman** [comment]
@macta I've not got time to review, so please forge ahead and merge.
@samWson Love to see those drawings when you are done - help me catch up with everything Tim has done.

**Comment by macta** [comment]
@bencoman @samWson - ok I'll plough on. Part of this has also been about learning the sweetspot with Iceberg (and there have been some bugs and confusion there) and the practicalities of Exercism. Anyway - its an interesting project, and actually the code is pretty much what we've always had - but as always with Smalltalk, you find better (I hope) places to put things and you spread the same code over more better described concepts.

Anyway - I'll merge, as this is too big.  I did tag the last version and update the instructions so people dont' get this until we've kicked the tires a bit.

**Pull request merged**
