### PR TITLE
Convert exercise tags to packages 

### PR DESCRIPTION
**Pull request by macta**
Currently a spike, and related to similar work @bencoman has done - we are collaborating to move the tags over to full packages to address #302

### CODE REVIEW

**Comment by bencoman** [comment]
Its seems you've done more than me in the conversion including supporting methods, so ignore my **fullPackage2** branch and just continue with yours.  Although I notice you went with Exercism@HelloWorld rather than Exercise@HelloWorld.

**Comment by macta** [comment]
@bencoman so I've got it working, with tests passing (although the coverage is still not quite idea). It will load both as a default baseline (and you can then load the dev baseline - what a pain to implement with so many packages - see the BaselineOf).

This will work with both old and new formats - so we can direct existing users to follow the upgrade steps we have already written (their existing exercises will stay and can still be submitted), but new ones will adopt the new package format.

Sorry - I misunderstood on the Prefix@Name, I thought you meant Exercism vs Exercise - but it should be quite easy to change it (as its a script). Do you want to do that?

**Comment by macta** [comment]
@bencoman thanks for chipping in on this, it makes it much easier having more minds on this. Let me know if you think exercise@helloworld resonates better - its a pretty simple fix, and then we can do a more testing and see how close we are to pushing something out.

**Comment by bencoman** [comment]
On Tue, 30 Apr 2019 at 01:36, Tim Mackinnon <notifications@github.com>
wrote:

> @bencoman <https://github.com/bencoman> thanks for chipping in on this,
> it makes it much easier having more minds on this. Let me know if you think
> exercise@helloworld resonates better
>
With capital 'E', yes I think it is better.

> - its a pretty simple fix, and then we can do a more testing
>
and see how close we are to pushing something out.
>
I've been wondering how we go about testing without impacting existing
users.
Perhaps temporarily generate a few like /exercise/zzz-experimental-anagram
so we ourselves can check it works as expected before exposing users to it.

cheers -ben

**Comment by RoelofWobben** [comment]
and im willing to helping with testing but I have to know which steps I have to takeso I get the new challenges

**Comment by macta** [comment]
@bencoman @RoelofWobben - I think this one is ready to merge into master, and along with Die (a custom exercise) we can prove it works with the upgrade instructions of new and old exercises

**Comment by RoelofWobben** [comment]
as far as I can test the upgrade and install instuctions still work.

**Comment by macta** [comment]
I'm going to merge this to get @RoelofWobben to help with testing as other pieces are starting to require it (like the TwoFer critics, and a few others neading extension methods)

**Pull request merged**
