### PR TITLE
Fixes #466 by specifying main branch

### LINKED ISSUE #466: [v2] Loading Exercism into Pharo image uses 'master' instead of 'main' branch
**Describe the bug**  
Based on intructions in docs/INSTALLATION.md, users should load Exercism v2 into Pharo image using following project spec/baseline (code responsible for loading/compiling Exercism into Pharo image):
```
Metacello new 
 baseline: 'Exercism'; 
 repository: 'github://exercism/pharo-smalltalk/releases/latest';
 load.
```
Curently this doesn't work (loading v2 Exercism fails), due to recent renaming of default branch to 'main' by Exercism maintainers. 
Iceberg (tool in Pharo for integration with Git and Github) uses by default 'master' branch for historical reasons and backward compatibility of existing community projects. Therefore 'main' branch has to be explicitly part of repository URL for loading Exercism project, in order to bypass hardcoded name of default branch.  Mitigation is to change instructions in docs/INSTALLATION.md, in order to avoid new users experiencing errors during loading Exercism by following:
```
Metacello new 
 baseline: 'Exercism'; 
 repository: 'github://exercism/pharo-smalltalk:main/releases/latest';
 load.
```

**Steps to reproduce the behavior**  
Follow instructions in docs/INSTALLATION.md: 
* Install Pharo on your computer
* Open Pharo and paste expression to load Exercism into Playground (REPL-like tool in Pharo)
* evaluate expression  

**Actual result:** Loading Exercism project fails with error.  
**Expected behavior:** Exercism project is loaded successfully.  

**Version information:**  
OS: all
Version of Exercism: v2
Version of Exercism/Pharo-Smalltalk: v0.2.10 (latest)

**Expected development cost**  
Minimal (just to change INSTALLATION.md)

### PR DESCRIPTION
**Pull request by edward**
Fixes #466 by specifying main branch

### CODE REVIEW

**Comment by edward** [comment]
It looks like some CI tools are misconfigured and are passing invalid flags to some tools causing them to crash.

**Comment by SleeplessByte** [comment]
Nah. They're still using the old configlet config I think :)

https://github.com/exercism/pharo-smalltalk/pull/467/checks?check_run_id=2078148642 can be fixed by removing `--track-id pharo`
https://github.com/exercism/pharo-smalltalk/pull/467/checks?check_run_id=2078148505 can be fixed by following the error messages, but I recommend ignoring this as part of this PR.

**Review by Bajger — APPROVED** [review]

**Comment by samWson** [comment]
@edward thanks for the PR. I'm going to fix the CI issues, then I'll get on to merging your fix.

**Comment by samWson** [comment]
@edward I've merged fixes to the CI config into `main`. I think you will need to pull from `main` to your remote repository and rebase your branch on `main` to get the checks passing.

**Comment by edward** [comment]
Ok! I’ll give that a shot. Thanks!

**Comment by samWson** [comment]
Configlet lint is failing because the `die` practice exercise doesn't have a `instructions.md` file. It's an experimental exercise contributed from the Pharo community. I'll work on it. Sorry @edward but you will have to do the same pull and rebase actions again after I've fixed this. I'll let you know when.

**Comment by edward** [comment]
Ok, thanks!!

So stoked to get this fixed.

**Comment by samWson** [comment]
OK @edward. I've merged #471. Pull from `main` to your repository and rebase on `main`, then push again. Then configlet lint should pass.

**Comment by edward** [comment]
@samWson Ok, done!

**Review by SleeplessByte — APPROVED** [review]

**Comment by SleeplessByte** [comment]
Since it was already the intention to get this merged, I'll just merge it so ya'll can continue on what you actually wanted to work on ;)

**Comment by samWson** [comment]
Thanks for that @SleeplessByte. Thanks for the contribution @edward.

**Pull request merged**
