### PR TITLE
Added backward compatibility for Pharo 8

### LINKED ISSUE #569: Error in getting solution path string in Pharo8
**Bug description**
Found by user, who was trying to fetch exercise on P8 version. Code is using method, which was introduced in later version (P9) but not in Pharo 8.

**To Reproduce**
1. Retrieve latest stable version of Pharo 8
2. Install Exercism project based on installation instructions
3. Fetch new exercise, e.g.: 'two-fer'
4. See error:
obrazek

**Expected behavior**
Two fer exercise is successfully fetched.

**Version information:**
 - OS:  any
 - Pharo Version 8

**Expected development cost**
Introduce #delimiter and put it to P8 compatibility package of baseline that calls older method #delimeter

### PR DESCRIPTION
**Pull request by Bajger**
- fixes #569

### CODE REVIEW

**Comment by Nezteb** [comment]
Confirmed working in the MOOC image! Previously I couldn't even fetch the `hello-world` exercise.

Screenshot 2023-03-19 at 1 49 10 PM

**Comment by Bajger** [comment]
@glennj: Hi Glenn! This is a small fix for Pharo 8. Please approve so I can merge PR. Thanks!

**Comment by Bajger** [comment]
> Those ExercismPharo* packages are baffling. I guess you just need to add ... whatever is needed to get it working.

> Would be nice to get feeling over time about what versions people are using to submit exercises. Version 7.x seems very old.

Thanks for your insight and I agree. P11 is going to be released soon. So it doesn't make sense to have backward compatibility for all of those past versions. I'll remove P7 support once P11 stable is introduced. I'll add a paragraph regarding Pharo version compatibility to installation instructions.

**Comment by Bajger** [comment]
@ErikSchierboom: Thanks for formal approval. I'll merge PR then.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
