### PR TITLE
409-Resolves problem with loading dependent classes within package(exercise)

### LINKED ISSUE #409: Exercism - problem with loading dependent classes within package/exercise
Greetings exercists!
I'm having trouble loading previously sumbitted Exercism exercise, which is in one package.
image

Issue here is that class definitions are stored within individual .st files and the load method do not resolve dependencies between classes. Is there a better way of load entire exercise package into the image, e.g. by loading entire package using TonelReader>>loadDefinitions method? 

Do you have idea, if TonelReader>>loadDefinitions resolves dependencies of same package implicitly? (I could probably test by myself :D)

If yes, then method for loading exercise could be changed to something like:
```
ExercismDownloadProgram>>installExerciseFor: submission

         (TonelReader on: submission sourcesDirectoryPath fileName: submission exerciseName ) loadDefinitions.
       		
	SystemAnnouncer uniqueInstance
		announce: (RPackageRegistered to: submission exercise exercisePackage).
	
```
But, I don't know if tonel reader expects already ordered .st files based on dependencies..hopefully not.

### PR DESCRIPTION
**Pull request by Bajger**
- fixes #409 
- this will effectively resolve loading exercise, where source files contain dependent classes (one class is subclass of another)
- Tonel format used in Pharo uses one file per class for serialization from/to git
- When subclass is loaded earlier than superclass, there was a problem with dependency
- New way uses MCSnapshot object, that resolves dependencies between class definitions and classes are loaded in proper order

### CODE REVIEW

**Comment by Bajger** [comment]
@glennj : I know it is pretty extensive code change, but this resolves loading dependent classes in same package. I did following:
- removed usage of TonelParser and replaced by TonelReader, which put class, method, class extension definitions in right order to be loaded, in the end, reader just uses parser internally
- used MCSnapshot to wrap definitions, in case there is a dependency, snapshot resolves that during installation
- added more unit tests on submission (which uses memory file reference with sources needed by tonel reader)

Reason: This would allow us to write exercises in more Smalltalk idiomatic way, since we can use multiple classes (that can subclass each other) 

It would be great, if you can test review command manually - I'm not the mentor at the moment
I will also test manually original code with new code and see if there are differences in download/submit operations (hope not)

**Comment by Bajger** [comment]
All unit tests green!

**Comment by Bajger** [comment]
Tested manually download on my solution of robot-simulator (that had dependencies), and tried submit back. Works well.

**Comment by Bajger** [comment]
@samWson : Hi Sam! I'm not sure how busy you are and if you're in mood to review. Your review is much appreciated!

**Comment by Bajger** [comment]
@macta, @bencoman I know you guys aren't much involved right now. Kindly asking for review of this, if you have some time. PR addresses one old issue and unifying approach with using Tonel Reader, Writer for loading / serialization of sources.

**Review by gypsydave5 — APPROVED** [review]

**Review by glennj — APPROVED** [review]
I'm not particularly qualified to review this, but I trust you know what you're doing and if my approval gets it unstuck...

**Comment by Bajger** [comment]
@gypsydave5 @glennj : Thank you both for reviews! I've invested quite a time of how to design code import/export capabilities using Tonel classes, so it should be consistent. Prior approach was simpler (since Parser is simpler), but TonelReader can be used as blackbox and takes care about order of loaded definitions. Other element used - MCSnapshot addresses dependenies between classes. Tests are passing and manual testing worked just fine, so it should be fine to merge PR.

**Comment by Bajger** [comment]
@SleeplessByte Thanks for merging! Failed P9 build is unrelated to these changes. Should be ok to merge.

**Comment by Bajger** [comment]
@ErikSchierboom Can I ask for merging PR? I'm not currently treated as track maintainer, but I'd be happy to merge PR (my time/effort spent on this) prior [new contributor policy](https://forum.exercism.org/t/freeing-our-maintainers-exercism-wide-changes-to-track-repositories/1109) is active. If you have any doubts, just let me know :-)

**Pull request merged**
