### PR TITLE
Removes unneeded external dependency as there is a WebBrowser access …

### PR DESCRIPTION
**Pull request by macta**
…in the core image

Move OSProcess as a dev only dependency as its only now needed for generating meta data via configlet

### CODE REVIEW

**Comment by macta** [comment]
@samWson @bencoman Hurrah - this should be solution to #140 as it was pointed out that there is a WebBrowser class in core pharo. I've tested it in a clean image, so am going to push it so some of our discord users can give it a spin. But Sam - I'm keen for you to then test #140 .

**Comment by macta** [comment]
fixes #148 (by removing the pre-req)

**Comment by samWson** [comment]
@macta I've tested on Windows 10 from scratch again and it seems to be working fine.

**Comment by macta** [comment]
Hurrah!!!!!!!

**Pull request merged**
