### PR TITLE
High Scores: small redesign to use an instance variable to hold the scores

### PR DESCRIPTION
**Pull request by glennj**
Many of the Pharo exercises don't particularly utilize objects to hold state. This PR separates the methods to add scores from the queries.

Also a couple of additional tests to validate the returned scores are copies.

### CODE REVIEW

**Comment by glennj** [comment]
I don't know why the travis build still shows as Pending: the details end with "Done. Your build exited with 0"

**Comment by samWson** [comment]
Hi @glennj. I'm back from my travel so now I have the time to go over your pull requests. Sorry you had to wait so long.

I like your alternative of using an instance variable to hold state. It fits the Object Oriented paradigm better. Changing the tests to use the new API however presents a problem.

The tests are designed to the same [specification](https://github.com/exercism/problem-specifications/blob/master/exercises/high-scores/canonical-data.json) that all the other language tracks use. For example this test case:
```json
  "cases": [
    {
      "description": "List of scores",
      "property": "scores",
      "input": {
        "scores": [30, 50, 20, 70]
      },
      "expected": [30, 50, 20, 70]
    },
```

The above case defines a method/function called `scores` that takes a collection as an argument and returns another collection i.e. `input` and `expected`. All the language tracks work to this specification which keeps them predictably the same but as you have discovered might not be a good fit for the language paradigm.

We can add alternative solutions to our collection of exercises. In that case we could call this class `HighScores2` (for an example see #392) . It would still need to pass the same tests i.e. same methods with the same arguments, which likely makes the use of an instance variable unnecessary.

The public API defined by the tests needs to stay the same as defined in the problem specification if we don't want to deviate from the rest of Exercism. I don't know if we have any flexibility to do this so I will raise another issue elsewhere to investigate this.

**Comment by samWson** [comment]
I see your point. If other language tracks are treating the problem specifications more generally then I am happy to as well.

There is one more step to do. Since you are changing the tests they will need to be regenerated according to [these instructions](https://github.com/exercism/pharo-smalltalk#publishing-a-completed-exercise-maintainers). That will create the text files for the tests that are needed for the Exercism website. Once that is done then we can get this merged.

**Comment by glennj** [comment]
@samWson a side note: are you aware you have the Allergies exercise stuck in the mentor queue? https://exercism.io/mentor/solutions/92f15e6369ac49178c166b78c72adb50

**Comment by samWson** [comment]
> @samWson a side note: are you aware you have the Allergies exercise stuck in the mentor queue? https://exercism.io/mentor/solutions/92f15e6369ac49178c166b78c72adb50

I see. I let this exercise slide ages ago. Simply put I couldn't solve it so I moved on to other exercises but I haven't done any exercises for months now. For now I'm wanting to spend more time on this repository as it has been left alone for too long. The previous mentor was inactive so that exercise was put back in the mentor queue.

**Review by Bajger — APPROVED** [review]
Looks ok, could be merged.

**Comment by Bajger** [comment]
@SleeplessByte: changes looks ok, but I don't see the conflicts to resolve merging PR. Can you see that?

**Comment by Bajger** [comment]
@SleeplessByte, thanks for instructions, still I can't see merge conflicts. I have following: 
```
gh pr status

Relevant pull requests in exercism/pharo-smalltalk

Current branch
  #400  High Scores: small redesign to use an instance ... [glennj:high-scores-more-OO]
  ✓ Checks passing - Review required

Created by you
  You have no open pull requests

Requesting a code review from you
  You have no pull requests to review
```
but if I do:
```
gh pr merge 400
X Pull request #400 is not mergeable: the merge commit cannot be cleanly created.
To have the pull request merged after all the requirements have been met, add the `--auto` flag.
```
Any thoughts?

**Comment by SleeplessByte** [comment]
Yes, rebasing it will/should make the conflicts show up :)

**Comment by Bajger** [comment]
I don't have a write access to this branch, so I should fork from Glennj's repo and make own branch out of his branch? Or maybe adding me to [.github/CODEOWNERS](https://github.com/exercism/pharo-smalltalk/tree/main/.github/CODEOWNERS) file would enable me to add more commits to this branch?

**Comment by Bajger** [comment]
@glennj : Is this exercise improvement something you'd like to discard? I can do new PR that would include these changes (I wasn't able to resolve conflicts with main).

**Comment by glennj** [comment]
Oops, that was an accident. Nevertheless, if you with to pursue it, you have my blessing.

**Pull request closed without merging**
