### PR TITLE
Add base implementation of Trinary exercise.

### PR DESCRIPTION
**Pull request by carlotxra**
Add base implementation of Trinary exercise.
Rename generated test methods

### CODE REVIEW

**Comment by macta** [comment]
This is cool - I'm on the road, but will also generate the exercism meta files tomorrow (ish) and we can push this one out. Appreciate the help

**Comment by carlotxra** [comment]
No problem. Still trying to understand the iceberg integration. Also see that travis broke for some reason.
Let me know if I missed something or if you want me to change something.

**Comment by macta** [comment]
Not sure why Travis broke - seems like a time-out just running the first test .

**Comment by macta** [comment]
Interesting - I see that you must have edited the test method names? They are a bit verbose - and it actually suggests an improvement to the generator, to only use the description name if there are multiple sub cases.

So I should fix the generator as if we need to regenerate, the names will revert back ....

**Comment by macta** [comment]
You've also highlighted another bug - as it turns out that Exercism has now deprecated Trinary - so I'll come back to this one and figure out if we can make it a bonus exercise.

**Comment by bencoman** [comment]
@macta what are your thoughts now on this one? (to clear PRs)

**Comment by macta** [comment]
I believe i fixed the generator based on what @carlotxra had done (its not identical but very close) - I'd be up for regenerating, apply the solution and making this a bonus exercise anyway - having lots to play with is good for folks like @RoelofWobben

**Comment by RoelofWobben** [comment]
why ?

**Comment by bencoman** [comment]
go ahead. regen would be better.

**Comment by Bajger** [comment]
Exercise deprecated, should be implemented by All Your Base exercise.

**Pull request closed without merging**
