### PR TITLE
Remove Travis CI integration

### LINKED ISSUE #429: Remove redundant Travis CI files
Exercism is moving from [Travis to Github Actions](https://github.com/exercism/exercism/issues/5396). This has been done for this repo by #427. We have had enough runs to see that it works so we can now remove the redundant files.

### PR DESCRIPTION
**Pull request by samWson**
Fixes #429 

This is not needed anymore since we are now using Github Actions.

The `.travis.yml` file made use of the `bin/fetch-configlet` script, which is not used anywhere else as far as I know.
I've left the script in place since it might be useful if a maintainer wants to make use of configlet on their
personal computer.

### CODE REVIEW

**Comment by samWson** [comment]
Hi @exercism/reviewers. Can I get this PR reviewed and approved please?

**Review by ekingery — APPROVED** [review]

**Comment by ekingery** [comment]
@iHiD I'll need write access if my review is to count for unblocking merge. Please let me know if there is a better procedure for this. Thanks!

**Review by SleeplessByte — APPROVED** [review]

**Comment by SleeplessByte** [comment]
Jeremy is likely out for 48 hours. Don't know if @ErikSchierboom is working on Monday. ⌛

**Review by iHiD — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]
> Don't know if @ErikSchierboom is working on Monday. ⌛

Mondays are my off-days :)

> The .travis.yml file made use of the bin/fetch-configlet script, which is not used anywhere else as far as I know.
> I've left the script in place since it might be useful if a maintainer wants to make use of configlet on their personal computer.

Excellent choice. It is definitely useful to also be able to run configlet locally.

**Pull request merged**
