### PR TITLE
Backported create class method from debugger  from P10 to P9

### LINKED ISSUE #503: Fix create class in the debugger for P9
While this is working for the original target version of Pharo (Pharo70), it's currently broken in Pharo90.

@RoelofWobben did some work on this today and found that the problem is _somewhere_ in the `ExercismPharo70` package. But where...? 🤔.

Might this also affect backward compatibility with Pharo70? And do we care?

### PR DESCRIPTION
**Pull request by Bajger**
- added compatibility package for P9 and included in Exercism baseline
- fixes #503

### CODE REVIEW

**Comment by Bajger** [comment]
This is backport of Pharo10 fix implemented in https://github.com/pharo-spec/NewTools/pull/309/files, tested on P9 (CI still uses P8, but it will be working soon on P9 once CI workflow action adoption is merged)

**Comment by Bajger** [comment]
@SleeplessByte Any update on reviewing this?

**Comment by Bajger** [comment]
@SleeplessByte , @ErikSchierboom Hi guys! Can you review, and merge PR? CI is passing, fix is tested, and seems ok.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by Bajger** [comment]
@ErikSchierboom : Thanks for approval! Can someone merge as well? I don't know, if I can get write access to this repo (what are the rules?)

**Comment by ErikSchierboom** [comment]
@Bajger The rules are that a person has to have been contributing a significant amount of work for over 6+ months to a repo.

**Pull request merged**
