### PR TITLE
Add section on collections from Reading Smalltalk PDF

### PR DESCRIPTION
**Pull request by samWson**
I figure since our solution for sum-of-multiples uses collections and iteration, this is a good place for this guide on collections. Taken again from the reading smalltalk PDF.

### CODE REVIEW

**Comment by samWson** [comment]
Hold on merging this for now. I think I've gone about this the wrong way. I've been adding to the exercise READMEs directly on Github, but now I see they are supposed to be generated from templates.

I'll look into generating these properly and undoing my manual edits to the READMEs.

**Comment by samWson** [comment]
@macta yes I'm going through that now. Looks like the right way for me to do this would be to add the text I want to the test class comment of an exercise then generate the README from there.

**Comment by samWson** [comment]
Just added a couple of commits to undo the manual edits I made to the READMEs. Instead I will use the removed text with the configlet tool to generate the READMEs properly.

**Comment by macta** [comment]
@samWson As I was updating the comments of the existing tests to match what the exercise generator does - I've applied your fixes in there. So I think this PR can be deleted when we approve that one.

**Comment by macta** [comment]
This is now obsolete as those comments were merged into the revlevent test comments. The exercise creation process is much easier now too.

**Pull request closed without merging**
