### PR TITLE
Document exercism API

### LINKED ISSUE #281: Document our use of Exercism REST API
This occurred to me as I was thinking about working on #245. The Exercism REST API, which we make use of, isn't documented. We have effectively discovered it ourselves through our work on this repo and properly documenting how we use it would help with future maintenance.

Documentation would also have the side benefit of being useful to the Exercism maintainers and any other language track maintainers who wished to use the API as well.

### PR DESCRIPTION
**Pull request by samWson**
Fixes #281.

This is work in progress for the moment. 

I've started with fetching exercises for now. Documenting the details of a `200` response is a bit difficult for me. I'm not that familiar with REST APIs and trying to get an idea of what it would look like from reading our own code is hard too.

Checking the exercism website source code has been very useful for getting the range of possible responses.

More to follow in this PR. The details of a `200` response need to be written and submitting exercises needs to be documented.

### CODE REVIEW

**Comment by macta** [comment]
This is great - particularly if its an itch you want to scratch to learn more.

Kind of related is: https://github.com/exercism/pharo-smalltalk/issues/255 as we aren't doing the http stuff very cleanly. There is also the question of why exercism doesn't use 302 vs 400 (as mentioned in: https://github.com/exercism/pharo-smalltalk/issues/281)

**Comment by samWson** [comment]
Added some more info. Still have the fine details of what the download and submit payloads look like to work out.

**Comment by samWson** [comment]
@macta @bencoman I'm thinking I might merge this PR as it is. I've managed to document quite a bit. The only thing missing is detail on submitting exercises which I can revisit later. Better to have this documentation as it is than not at all.

Have a look and let me know what you think.

**Comment by macta** [comment]
Sure - I also just answered a question from Ben on generation - might be worth having a read and possibly folding it in to this?

**Comment by bencoman** [comment]
@samWson I read the final in master:/docs.  Very nice.  I particularly like you sussed out the info on the return codes - they were unclear to me.

Only minor suggestion, `<name>` might be better as `<slug>`, for how Exercism refers to the kebab-case version of the exercise name.

**Comment by samWson** [comment]
@bencoman thanks for the feedback. I'll make a fix. I'm taking the opportunity now to try the exercises myself. It's why I wanted this language track in the first place.

**Pull request merged**
